# Generated by Django 4.0.3 on 2022-08-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_like_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="profile",
        ),
    ]
