# Generated by Django 4.1.1 on 2022-10-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_user_comment_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="user",
            new_name="profile",
        ),
    ]
