# Generated by Django 4.1.1 on 2022-10-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_rename_user_like_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="content",
        ),
    ]
