# Generated by Django 4.0.3 on 2022-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="No Bio..", max_length=300),
        ),
    ]
